# Generated by Django 4.1.3 on 2022-11-18 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideacomment',
            name='title',
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='publish_date',
            field=models.DateTimeField(default=datetime.date(2022, 1, 1)),
        ),
    ]
