# Generated by Django 4.1.3 on 2022-11-18 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_ideacomment_title_ideacomment_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidea',
            name='publish_date',
            field=models.DateTimeField(default=datetime.date(2022, 1, 1)),
        ),
    ]
