# Generated by Django 4.1.3 on 2022-11-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_businessidea_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessidea',
            name='publish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
